### ISSUE TITLE
Error: Nuklear library is not found. Please, install Nuklear 4.01

### ISSUE THREAD

**Issue by burner** [gecko0307/dagon-sandbox#1]
Hi,

I tried to build your project and got the above mentioned error.
I'm on arch linux x64.
I did run:

```
dub run resovle
dub build
./dagon-sandbox
```

Thank you

**Comment by gecko0307** [comment]
It requires Nuklear UI library: https://github.com/Immediate-Mode-UI/Nuklear, that should be installed to `/usr/local/lib/`

**Comment by Timu5** [comment]
You need to prebuild nuklear, first make sure you have cmake installed then:
`git clone https://github.com/Timu5/bindbc-nuklear`
`cd bindbc-nuklear`
`./prebuild.sh`
`sudo cp ./lib/libnuklear.so.4.1.5 /usr/local/lib/nuklear.so`
Done.

**Comment by burner** [comment]
that got it compile, but now it crashes with a segfault. I'll investigate when I find the time
